export function generateMakefile(project, selectedFiles, compilerFlags, compiler, sourceDir, objectDir, libs, includeDir, dependencies, valgrind, gdb) {
    let makefile = '';
    // makefile += `# Generated by makefile-generator you can find it at\n\n`
    makefile += `NAME\t:= ${project}\n`
    makefile += `\n`
    makefile += `SRC_DIR\t:= ${sourceDir}\n`
    makefile += `OBJ_DIR\t:= ${objectDir}\n`
    if (dependencies) {
        for (let dep of dependencies.split(" ")) {
            makefile += `${dep.toUpperCase()}_D\t:= ${dep}\n`
        }
    }
    makefile += `\n`
    makefile += `CC\t\t:= ${compiler}\n`
    makefile += `CFLAGS\t:= ${compilerFlags}\n`
    makefile += `\n`
    makefile += `INCLUDE\t:= -I ${includeDir}`
    if (libs[0]) {
        makefile += `\nLDFLAGS\t:=`
        for (let lib of libs) {
            makefile += ` -l${lib}`
        }
    }
    if (dependencies) {
        for (let dep of dependencies.split(" ")) {
            makefile += ` -I $(${dep.toUpperCase()}_D)/include`
        }
        makefile += `\nLDLIBS\t:=`
        for (let dep of dependencies.split(" ")) {
            // makefile += ` $(${dep.toUpperCase()}_D)/${dep}.a`
            makefile += ` -L $(${dep.toUpperCase()}_D) -l${dep}`
        }
    }
    makefile += `\n`
    makefile += `\n`
    makefile += `SRC\t\t:= ${selectedFiles.join(" ")}\n`
    makefile += `OBJ\t\t:= $(SRC:%.c=$(OBJ_DIR)/%.o)\n`
    makefile += `\n`
    makefile += `GREEN\t:= \\033[1;32m\n`
    makefile += `\n`
    makefile += `all: $(NAME)\n`
    makefile += `\n`
    makefile += `$(NAME): $(OBJ)\n`
    makefile += `\t@$(CC) $(OBJ) -o $(NAME)`
    if (libs[0])
        makefile += ` $(LDFLAGS)`
    if (dependencies[0])
        makefile += ` $(LDLIBS)`
    makefile += ` && printf \"$(GREEN)✔️ $(NAME)[0m compiled\\n\"\n`
    makefile += `\n`
    makefile += `$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c\n`
    makefile += `\t@mkdir -p $(OBJ_DIR)\n`
    makefile += `\t@$(CC) $(CFLAGS) -o $@ -c $< && printf \"$(GREEN)✔️ $(notdir $<)[0m compiled\\n\"\n`
    makefile += `\n`
    makefile += `run: $(NAME)\n`
    makefile += `\t@./$(NAME)\n`
    makefile += `\n`
    makefile += `clean:\n`
    makefile += `\t@rm -rf $(OBJ_DIR)\n`
    makefile += `\n`
    makefile += `fclean: clean\n`
    makefile += `\t@rm -f $(NAME)\n`
    makefile += `\n`
    makefile += `re: clean all\n`
    makefile += `\n`
    if (valgrind) {
        makefile += `valgrind: $(NAME)\n`
        makefile += `\t@valgrind  --show-leak-kinds=all --leak-check=full --track-origins=yes ./$(NAME)\n`
        makefile += `\n`
    }
    if (gdb) {
        makefile += `gdb: $(NAME)\n`
        makefile += `\t@gdb ./$(NAME)\n`
        makefile += `\n`
    }
    makefile += `.PHONY: all clean fclean re run`
    if (valgrind)
        makefile += ` valgrind`
    if (gdb)
        makefile += ` gdb`
    return makefile;
}